kind: Deployment
apiVersion: apps/v1
metadata:
    name: web-dpl
spec:
    replicas: 3
    selector:
        matchLabels:
            app: web
    template:
        metadata:
            labels:
                app: web
        spec:
            containers:
            -   image: web-image:test1.0
                name: web-container
                ports:
                -   containerPort: 80